### PR TITLE
Fix broken tests for _proof.html view

### PR DESCRIPTION
**Pull request by alexdesi**
### What?
Fix broken tests for _proof.html view

### CODE REVIEW

**Comment by willfish** [comment]
Not sure I understand this. What's going on here @alexdesi?

**Review by jebw — APPROVED** [review]
@willfish This should resolve the failing specs on `main`

The partial had been changed to rely on global state (a `@search`) variable - presumably this change got merged with failing specs? This mocks out that state resolving the failing specs

In general, since this is a partial and not a page template I think it might be better if the partial was changed to rely upon locals being explicitly passed into it, rather then assuming the presence of global state? 

@alexdesi would be good if you could fix the rubocop failure prior to merge - this doesn't relate to your change but should be a one liner to correct

**Comment by alexdesi** [comment]
Guys, since we are already using VCR on the views, and since the relevant cassette does exist,
I am using VCR.

Rubocop fixed.

**Review by jebw — APPROVED** [review]
LGTM

**Pull request merged**
