### PR TITLE
HOTT-1192: Removes maxlength from import export dates

### PR DESCRIPTION
**Pull request by willfish**
### Jira link

https://transformuk.atlassian.net/browse/HOTT-1192

### What?

I have added/removed/altered:

- [x] Removed maxlength option from formbuilder for import export date form

### Why?

I am doing this because:

- See for a rationale https://github.com/DFE-Digital/govuk-formbuilder/pull/329#issuecomment-986008839

### CODE REVIEW

**Comment by willfish** [comment]
@madviv I don't want to merge this without chatting to you. Lets walk the conversation in my PR (see link it Why)

**Review by jebw — CHANGES_REQUESTED** [review]
Looks good - can we also swap back to gem release of form builder

**Comment by willfish** [comment]
Sure

**Review by jebw — APPROVED** [review]
LGTM

**Pull request merged**
